{
    'name': "Cars Agency",
    'version': '17.0.1.1',
    'category': 'Sales',
    'author': 'Mabrouka',
    'license': 'LGPL-3',
    'depends':['base','mail'],
    "data": ["security/ir.model.access.csv",
             "views/car_brand_model.xml",
             "views/customer_model.xml",
             "views/car_model.xml",
             "views/request_model.xml",
             "views/agency_model.xml",
             "views/res_users_views.xml",
             "views/car_damaged_wizard.xml",
             "views/menus.xml",
             "data/data.xml",
             "data/mail_data.xml",
             "data/cron.xml",
             "report/car_agency_report.xml",
             "report/car_request_report.xml",
             "security/security.xml",
             ],

}